"""Canonical supervised-write input schemas; execution remains in registered handlers."""
from __future__ import annotations

from typing import Any

from path_to_skill_controller import PATH_TO_SKILL_WRITE_INPUT_SCHEMA
from unity_read_input_schemas import UNITY_READ_TOOL_INPUT_SCHEMAS
from unity_shared_input_schemas import (
    ANIMATION_CURVE_WRITE_PUBLIC_INPUT_SCHEMA,
    AVATAR_DESCRIPTOR_WRITE_PUBLIC_INPUT_SCHEMA,
    EXPRESSION_MENU_MANAGE_PUBLIC_INPUT_SCHEMA,
    EXPRESSION_PARAMETERS_MANAGE_PUBLIC_INPUT_SCHEMA,
    MANAGE_FX_ANIMATOR_PUBLIC_INPUT_SCHEMA,
    MATERIAL_TEXTURE_ASSIGNMENT_PUBLIC_INPUT_SCHEMA,
    RENDERER_MATERIAL_SLOT_PUBLIC_INPUT_SCHEMA,
    SCENE_ASSET_DUPLICATE_PUBLIC_INPUT_SCHEMA,
    SCENE_OBJECT_DUPLICATE_PUBLIC_INPUT_SCHEMA,
    TEXTURE_IMPORT_SETTINGS_PUBLIC_INPUT_SCHEMA,
    _PROJECT_PATH_PROPERTY,
)


EXTERNAL_MCP_WRITE_TOOL_INPUT_SCHEMAS: dict[str, dict[str, Any]] = {
    "vrcforge_scene_save": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath", "action", "scenePath"],
        "properties": {
            "projectPath": _PROJECT_PATH_PROPERTY,
            "action": {"type": "string", "enum": ["save", "save_as"]},
            "scenePath": {"type": "string", "pattern": "^Assets/.*\\.unity$", "description": "Exact active scene identity; never a hierarchy-path fallback."},
            "destinationScenePath": {"type": "string", "pattern": "^Assets/.*\\.unity$", "description": "Required only for save_as and must not exist."},
        },
    },
    "vrcforge_scene_transition": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath", "action"],
        "properties": {
            "projectPath": _PROJECT_PATH_PROPERTY,
            "action": {"type": "string", "enum": ["open_single", "open_additive", "new_saved", "set_active", "unload", "reload_saved"]},
            "scenePath": {"type": "string", "pattern": "^Assets/.*\\.unity$"},
            "destinationScenePath": {"type": "string", "pattern": "^Assets/.*\\.unity$", "description": "Required only for new_saved and must not exist."},
        },
    },
    "vrcforge_texture_patch": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath", "sourceTexturePath", "targetTexturePath", "region", "red", "green", "blue", "alpha", "opacity", "featherPixels"],
        "properties": {
            "projectPath": _PROJECT_PATH_PROPERTY,
            "sourceTexturePath": {"type": "string", "pattern": "^Assets/.*\\.png$"},
            "targetTexturePath": {"type": "string", "pattern": "^Assets/.*\\.png$", "description": "Create-new output; it and its .meta must be absent."},
            "region": {"type": "array", "minItems": 4, "maxItems": 4, "items": {"type": "integer", "minimum": 0}, "description": "Exact [x,y,width,height] pixel rectangle; width and height must be positive."},
            "protectedRegions": {"type": "array", "maxItems": 128, "items": {"type": "array", "minItems": 4, "maxItems": 4, "items": {"type": "integer", "minimum": 0}}},
            "red": {"type": "integer", "minimum": 0, "maximum": 255},
            "green": {"type": "integer", "minimum": 0, "maximum": 255},
            "blue": {"type": "integer", "minimum": 0, "maximum": 255},
            "alpha": {"type": "integer", "minimum": 0, "maximum": 255},
            "opacity": {"type": "number", "minimum": 0, "maximum": 1, "default": 1},
            "featherPixels": {"type": "integer", "minimum": 0, "maximum": 256, "default": 0},
        },
    },
    "vrcforge_user_adjustment_handoff": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath", "action", "mode", "avatarGlobalObjectId", "targetGlobalObjectId"],
        "properties": {
            "projectPath": _PROJECT_PATH_PROPERTY,
            "action": {"type": "string", "enum": ["prepare", "finalize", "abort"]},
            "mode": {"type": "string", "enum": ["transform", "skinned_bone_proxy", "constraint_bound", "physbone_chain"]},
            "avatarGlobalObjectId": {"type": "string", "pattern": "^GlobalObjectId_V1-"},
            "targetGlobalObjectId": {"type": "string", "pattern": "^GlobalObjectId_V1-"},
            "handoffId": {"type": "string", "pattern": "^[0-9a-f]{32}$"},
        },
    },
    "vrcforge_remap_skinned_mesh_bone": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath", "gameObjectPath", "componentIndex", "boneIndex", "expectedCurrentBonePath", "targetBonePath", "expectedMeshName", "preview"],
        "properties": {
            "projectPath": {"type": "string"},
            "gameObjectPath": {"type": "string"},
            "componentIndex": {"type": "integer", "minimum": 0},
            "boneIndex": {"type": "integer", "minimum": 0},
            "expectedCurrentBonePath": {"type": "string"},
            "targetBonePath": {"type": "string"},
            "expectedMeshName": {"type": "string"},
            "preview": {"type": "boolean"},
        },
    },
    "vrcforge_duplicate_scene_object": SCENE_OBJECT_DUPLICATE_PUBLIC_INPUT_SCHEMA,
    "vrcforge_duplicate_scene_asset": SCENE_ASSET_DUPLICATE_PUBLIC_INPUT_SCHEMA,
    "vrcforge_write_avatar_descriptor": AVATAR_DESCRIPTOR_WRITE_PUBLIC_INPUT_SCHEMA,
    "vrcforge_write_animation_curve": ANIMATION_CURVE_WRITE_PUBLIC_INPUT_SCHEMA,
    "vrcforge_manage_expression_parameters": EXPRESSION_PARAMETERS_MANAGE_PUBLIC_INPUT_SCHEMA,
    "vrcforge_manage_expression_menu": EXPRESSION_MENU_MANAGE_PUBLIC_INPUT_SCHEMA,
    "vrcforge_remove_component": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath", "gameObjectPath", "componentType"],
        "properties": {
            "projectPath": _PROJECT_PATH_PROPERTY,
            "gameObjectPath": {"type": "string"},
            "componentType": {"type": "string"},
            "componentIndex": {"type": "integer", "minimum": 0, "default": 0},
        },
    },
    "vrcforge_reparent_gameobject": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath", "gameObjectPath"],
        "properties": {
            "projectPath": _PROJECT_PATH_PROPERTY,
            "gameObjectPath": {"type": "string"},
            "newParentPath": {"type": "string"},
            "worldPositionStays": {"type": "boolean", "default": True},
        },
    },
    "vrcforge_set_gameobject_active": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath", "gameObjectPath", "active"],
        "properties": {
            "projectPath": _PROJECT_PATH_PROPERTY,
            "gameObjectPath": {"type": "string"},
            "active": {"type": "boolean"},
        },
    },
    "vrcforge_set_property": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath", "gameObjectPath", "componentType", "propertyPath", "value"],
        "properties": {
            "projectPath": _PROJECT_PATH_PROPERTY,
            "gameObjectPath": {"type": "string"},
            "componentType": {"type": "string"},
            "propertyPath": {"type": "string"},
            "value": {"description": "Exact JSON value to assign to the field or property."},
            "componentIndex": {"type": "integer", "minimum": 0, "default": 0},
        },
    },
    "vrcforge_save_current_scene": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath", "scenePath"],
        "properties": {
            "projectPath": {
                "type": "string",
                "description": "Exact existing Unity project root whose current saved scene must be dirty.",
            },
            "scenePath": {
                "type": "string",
                "pattern": "^Assets/.*\\.unity$",
                "description": "Exact current Assets/... .unity path used as an identity check.",
            },
        },
    },
    "vrcforge_create_installed_skill": {
        "type": "object",
        "additionalProperties": False,
        "required": ["name", "description", "instructions"],
        "properties": {
            "name": {"type": "string", "pattern": "^[a-z][a-z0-9_.-]{1,80}$"},
            "title": {"type": "string", "maxLength": 120},
            "description": {"type": "string", "minLength": 1, "maxLength": 500},
            "instructions": {"type": "string", "minLength": 1, "maxLength": 262144},
            "allowedTools": {
                "type": "array", "items": {"type": "string"}, "maxItems": 64
            },
            "entrypointTool": {"type": "string"},
            "permissionMode": {
                "type": "string",
                "enum": ["instruction_only", "read_only", "preview", "approval_required"],
            },
            "riskLevel": {"type": "string", "enum": ["low", "medium", "high"]},
            "whenToUse": {"type": "string", "maxLength": 1000},
            "tags": {"type": "array", "items": {"type": "string"}, "maxItems": 32},
        },
    },
    "vrcforge_write_path_to_skill": PATH_TO_SKILL_WRITE_INPUT_SCHEMA,
    "vrcforge_set_skill_package_enabled": {
        "type": "object",
        "additionalProperties": False,
        "required": ["skillPackageId", "enabled"],
        "properties": {
            "skillPackageId": {"type": "string", "minLength": 1},
            "enabled": {"type": "boolean"},
        },
    },
    "vrcforge_import_skill_package": {
        "type": "object",
        "additionalProperties": False,
        "required": ["packagePath"],
        "properties": {
            "packagePath": {"type": "string", "description": "Exact local path to the existing .vsk package."},
            "source": {"type": "string", "maxLength": 160, "description": "Optional audit label for this local import."},
            "projectToUserSkills": {"type": "boolean", "default": True, "description": "Project the installed package into the user Skill directory."},
        },
    },
    "vrcforge_export_skill_package": {
        "type": "object",
        "additionalProperties": False,
        "required": ["skillName", "outputPath"],
        "properties": {
            "skillName": {"type": "string", "description": "Exact installed user Skill name to export."},
            "outputPath": {"type": "string", "description": "Exact new local .vsk destination; it must not already exist."},
            "release": {"type": "boolean", "default": False, "description": "Sign a release package instead of creating a development package."},
            "privateKeyPath": {"type": "string", "description": "Local Ed25519 private-key file path required only for release export. Key material is never accepted inline."},
        },
    },
    "vrcforge_set_texture_import_settings": TEXTURE_IMPORT_SETTINGS_PUBLIC_INPUT_SCHEMA,
    "vrcforge_manage_fx_animator": MANAGE_FX_ANIMATOR_PUBLIC_INPUT_SCHEMA,
    "vrcforge_set_material_shader": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath", "rendererPath", "slotIndex", "shaderName"],
        "properties": {
            "projectPath": {"type": "string", "description": "Exact existing Unity project root bound to this material write."},
            "rendererPath": {"type": "string", "description": "Exact loaded-scene renderer hierarchy path used to resolve the material slot."},
            "rendererComponentId": {"type": "string", "description": "Optional exact renderer identity returned by the preview."},
            "materialAssetPath": {"type": "string", "description": "Optional exact Assets/... .mat path used to disambiguate the selected slot."},
            "slotIndex": {"type": "integer", "minimum": 0, "description": "Zero-based material slot index on the selected renderer."},
            "shaderName": {"type": "string", "description": "Exact installed Unity shader name to assign."},
            "shaderAssetPath": {"type": "string", "description": "Optional exact Assets/... or Packages/... shader asset path used to bind the preview."},
        },
    },
    "vrcforge_set_material_texture": MATERIAL_TEXTURE_ASSIGNMENT_PUBLIC_INPUT_SCHEMA,
    "vrcforge_set_renderer_material_slot": RENDERER_MATERIAL_SLOT_PUBLIC_INPUT_SCHEMA,
    "vrcforge_set_constraint_sources": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath", "scenePath", "gameObjectPath", "constraintKind", "componentIndex", "sources"],
        "properties": {
            "projectPath": {"type": "string", "description": "Exact existing Unity project root bound to this scene write."},
            "scenePath": {"type": "string", "description": "Exact Assets/... .unity scene containing the constraint."},
            "gameObjectPath": {"type": "string", "description": "Exact hierarchy path of the GameObject carrying the constraint."},
            "constraintKind": {"type": "string", "enum": ["position", "rotation", "scale", "parent", "aim", "look_at"]},
            "componentIndex": {"type": "integer", "minimum": 0, "maximum": 31},
            "sources": {
                "type": "array",
                "maxItems": 64,
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["sourcePath", "weight"],
                    "properties": {
                        "sourcePath": {"type": "string", "description": "Exact source Transform hierarchy path."},
                        "weight": {"type": "number", "minimum": 0.0, "maximum": 1.0},
                    },
                },
            },
        },
    },
    "vrcforge_save_scene_object_as_prefab": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath", "sourceScenePath", "sourceObjectPath", "prefabAssetPath"],
        "properties": {
            "projectPath": {"type": "string", "description": "Exact existing Unity project root bound to this create-new asset write."},
            "sourceScenePath": {"type": "string", "description": "Exact Assets/... .unity scene containing the source object."},
            "sourceObjectPath": {"type": "string", "description": "Exact hierarchy path of the source scene object."},
            "prefabAssetPath": {"type": "string", "description": "Exact absent Assets/VRCForge/Generated/... .prefab destination."},
        },
    },
    "vrcforge_build_parameter_bit_packed_clone": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath", "sourceScenePath", "sourceAvatarPath", "outputCloneName"],
        "properties": {
            "projectPath": {"type": "string", "description": "Exact existing Unity project root bound to this source-preserving optimization."},
            "sourceScenePath": {"type": "string", "description": "Exact Assets/... .unity scene containing the source Avatar."},
            "sourceAvatarPath": {"type": "string", "description": "Exact source Avatar hierarchy path; the source is preserved."},
            "outputCloneName": {"type": "string", "description": "Exact new sibling clone name for the packed result."},
        },
    },
    "vrcforge_atomic_reference_rename": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath", "operationKind", "scenePath", "avatarPath"],
        "oneOf": [
            {"properties": {"operationKind": {"const": "game_object"}}, "required": ["targetObjectPath", "newName"]},
            {"properties": {"operationKind": {"const": "parameter"}}, "required": ["oldParameterName", "newParameterName"]},
        ],
        "properties": {
            "projectPath": {"type": "string", "description": "Exact existing Unity project root bound to this complete reference migration."},
            "operationKind": {"type": "string", "enum": ["game_object", "parameter"]},
            "scenePath": {"type": "string", "description": "Exact Assets/... .unity scene containing the Avatar."},
            "avatarPath": {"type": "string", "description": "Exact Avatar root hierarchy path that bounds the migration."},
            "targetObjectPath": {"type": "string", "description": "Exact descendant hierarchy path for a game_object migration."},
            "newName": {"type": "string", "description": "New leaf GameObject name for a game_object migration."},
            "oldParameterName": {"type": "string", "description": "Exact existing expression/Animator parameter name."},
            "newParameterName": {"type": "string", "description": "Exact replacement parameter name."},
        },
    },
    "vrcforge_delete_gameobject": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath"],
        "anyOf": [
            {"required": ["gameObjectPath"]},
            {"required": ["globalObjectId"]},
        ],
        "properties": {
            "projectPath": {"type": "string", "description": "Exact existing Unity project root bound to this external write call."},
            "gameObjectPath": {"type": "string", "description": "Exact hierarchy path when it is unique."},
            "globalObjectId": {"type": "string", "description": "Exact Unity GlobalObjectId; prefer this when hierarchy names are duplicated."},
            "preview": {"type": "boolean", "default": False},
        },
    },
    "vrcforge_instantiate_prefab": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath"],
        "anyOf": [
            {"required": ["assetPath"]},
            {"required": ["guid"]},
        ],
        "properties": {
            "projectPath": {"type": "string", "description": "Exact existing Unity project root bound to this external write call."},
            "assetPath": {"type": "string", "description": "Exact project-relative prefab asset path, including Packages/... prefabs."},
            "guid": {"type": "string", "description": "Exact prefab asset GUID when assetPath is omitted."},
            "parentPath": {"type": "string", "description": "Optional exact hierarchy path of the parent. Omit or pass an empty string for the scene root."},
            "name": {"type": "string", "description": "Optional exact instance name override."},
            "worldPositionStays": {"type": "boolean", "default": True},
            "preview": {"type": "boolean", "default": False},
        },
    },
    "vrcforge_build_test_avatar": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath", "avatarPath"],
        "properties": {
            "projectPath": {"type": "string", "description": "Exact existing Unity project root bound to this local build."},
            "avatarPath": {"type": "string", "description": "Exact loaded-scene hierarchy path of the avatar to Build & Test locally."},
        },
    },
    "vrcforge_build_and_upload_avatar": {
        **UNITY_READ_TOOL_INPUT_SCHEMAS.get("vrcforge_avatar_upload_readiness", {}),
        "required": [
            "projectPath", "avatarPath", "uploadMode", "buildType", "platforms", "metadata", "thumbnail",
            "expectedAvatarGlobalObjectId", "expectedCurrentPipelineId", "expectedSdkUserId", "expectedPlatform", "readinessDigest",
        ],
        "properties": {
            **UNITY_READ_TOOL_INPUT_SCHEMAS.get("vrcforge_avatar_upload_readiness", {}).get("properties", {}),
            "expectedAvatarGlobalObjectId": {"type": "string"},
            "expectedCurrentPipelineId": {"type": "string"},
            "expectedSdkUserId": {"type": "string"},
            "expectedPlatform": {"type": "string"},
            "readinessDigest": {"type": "string", "pattern": "^[0-9a-fA-F]{64}$"},
        },
    },
    "vrcforge_convert_unity_constraint": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath", "scenePath", "avatarPath", "gameObjectPath", "componentType", "componentIndex", "expectedSceneGuid", "expectedSceneFileDigest", "expectedAvatarGlobalObjectId", "expectedComponentGlobalObjectId", "expectedBeforeDigest"],
        "properties": {
            **UNITY_READ_TOOL_INPUT_SCHEMAS.get("vrcforge_preview_unity_constraint_conversion", {}).get("properties", {}),
            "expectedSceneGuid": {"type": "string"},
            "expectedSceneFileDigest": {"type": "string", "pattern": "^[0-9a-fA-F]{64}$"},
            "expectedAvatarGlobalObjectId": {"type": "string"},
            "expectedComponentGlobalObjectId": {"type": "string"},
            "expectedBeforeDigest": {"type": "string", "pattern": "^[0-9a-fA-F]{64}$"},
        },
    },
    "vrcforge_install_unity_core": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath"],
        "properties": {
            "projectPath": {
                "type": "string",
                "description": "Exact existing Unity project root that will receive the Core bundled with this running VRCForge build.",
            },
        },
    },
    "vrcforge_gesture_manager_set_parameter": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath", "parameterName", "value"],
        "properties": {
            "projectPath": {"type": "string", "description": "Exact existing Unity project root bound to this external write call."},
            "avatarPath": {"type": "string", "description": "Optional exact avatar hierarchy path; required only when multiple managers are connected."},
            "parameterName": {"type": "string", "description": "Exact existing Gesture Manager runtime parameter, for example VelocityZ or Grounded."},
            "value": {"type": "number", "description": "Runtime value; the tool reads back the applied value."},
        },
    },
    "vrcforge_gesture_manager_enter_play_mode": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath"],
        "properties": {
            "projectPath": {"type": "string", "description": "Exact existing Unity project root bound to this external editor-state call."},
            "avatarPath": {"type": "string", "description": "Optional exact active avatar hierarchy path; required when multiple active avatars exist."},
        },
    },
    "vrcforge_capture_screenshot": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath"],
        "properties": {
            "projectPath": {"type": "string", "description": "Exact existing Unity project root bound to this capture."},
            "avatarPath": {"type": "string", "description": "Optional exact avatar hierarchy path; omit only when the active avatar is unambiguous."},
            "cameraMode": {"type": "string", "enum": ["framed", "free"], "default": "framed"},
            "cameraPosition": {"$ref": "#/$defs/vector3"},
            "targetPosition": {"$ref": "#/$defs/vector3"},
            "upVector": {"$ref": "#/$defs/vector3"},
            "projection": {"type": "string", "enum": ["perspective", "orthographic"]},
            "orthographicSize": {"type": "number", "exclusiveMinimum": 0},
            "fieldOfView": {"type": "number", "exclusiveMinimum": 0, "maximum": 179},
            "angle": {
                "type": "string",
                "enum": ["front", "side_left", "side_right", "back", "bottom"],
                "description": "One fixed view angle. bottom is a true underneath view. Do not combine a named angle with pitch, yaw, or roll.",
            },
            "framing": {
                "type": "string",
                "enum": ["face", "avatar"],
                "description": "face frames the head; avatar frames the complete avatar including feet and tail. Named angles default to face for compatibility.",
            },
            "captureScope": {
                "type": "string",
                "enum": ["face", "avatar"],
                "description": "Exact Core capture scope. It is an alias of framing and must match framing when both are supplied.",
            },
            "pitch": {
                "type": "number",
                "minimum": -180.0,
                "maximum": 180.0,
                "description": "Explicit camera pitch in degrees. Do not combine with angle.",
            },
            "yaw": {
                "type": "number",
                "minimum": -180.0,
                "maximum": 180.0,
                "description": "Explicit camera yaw in degrees. Do not combine with angle.",
            },
            "roll": {
                "type": "number",
                "minimum": -180.0,
                "maximum": 180.0,
                "description": "Explicit camera roll in degrees. Do not combine with angle.",
            },
            "width": {"type": "integer", "minimum": 256, "maximum": 2048, "default": 960},
            "height": {"type": "integer", "minimum": 256, "maximum": 2048, "default": 960},
            "requirePlayMode": {"type": "boolean", "default": False},
            "captureMode": {
                "type": "string",
                "enum": ["auto", "scene_view", "game_view"],
                "default": "auto",
                "description": "scene_view captures the Unity Scene view even during Gesture Manager Play Mode.",
            },
        },
        "$defs": {"vector3": {"type": "object", "additionalProperties": False, "required": ["x", "y", "z"], "properties": {"x": {"type": "number"}, "y": {"type": "number"}, "z": {"type": "number"}}}},
        "allOf": [
            {"if": {"properties": {"cameraMode": {"const": "free"}}}, "then": {"required": ["cameraMode", "cameraPosition", "targetPosition", "upVector", "projection"], "oneOf": [{"properties": {"projection": {"const": "perspective"}}, "required": ["fieldOfView"], "not": {"required": ["orthographicSize"]}}, {"properties": {"projection": {"const": "orthographic"}}, "required": ["orthographicSize"], "not": {"required": ["fieldOfView"]}}]}},
            {"if": {"properties": {"cameraMode": {"const": "framed"}}}, "then": {"not": {"anyOf": [{"required": ["cameraPosition"]}, {"required": ["targetPosition"]}, {"required": ["upVector"]}, {"required": ["projection"]}, {"required": ["orthographicSize"]}, {"required": ["fieldOfView"]}]}}}
        ],
    },
    "vrcforge_capture_multi_screenshot": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath"],
        "properties": {
            "projectPath": {"type": "string"},
            "avatarPath": {"type": "string"},
            "angles": {
                "type": "array",
                "items": {"type": "string", "enum": ["front", "side_left", "side_right", "back", "bottom"]},
                "default": ["front", "side_left", "side_right", "back", "bottom"],
                "minItems": 1,
                "maxItems": 5,
                "uniqueItems": True,
            },
            "framing": {"type": "string", "enum": ["face", "avatar"]},
            "width": {"type": "integer", "minimum": 256, "maximum": 2048, "default": 960},
            "height": {"type": "integer", "minimum": 256, "maximum": 2048, "default": 960},
            "requirePlayMode": {"type": "boolean", "default": False},
            "captureMode": {"type": "string", "enum": ["auto", "scene_view", "game_view"], "default": "auto"},
        },
    },
    "vrcforge_select_scene_object": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath", "gameObjectPath"],
        "properties": {
            "projectPath": {"type": "string", "description": "Exact existing Unity project root bound to this external write call."},
            "gameObjectPath": {"type": "string", "description": "Exact loaded-scene hierarchy path to select and show in Inspector."},
        },
    },
    "vrcforge_set_play_mode": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath", "isPlaying"],
        "properties": {
            "projectPath": {"type": "string", "description": "Exact existing Unity project root bound to this external write call."},
            "isPlaying": {"type": "boolean", "description": "True to enter Play Mode; false to exit Play Mode."},
        },
    },
    "vrcforge_confirm_unity_reload_dialog": {
        "type": "object",
        "additionalProperties": False,
        "required": ["projectPath", "confirmReload"],
        "properties": {
            "projectPath": {
                "type": "string",
                "description": "Exact existing Unity project whose bound Editor displays the Reload dialog.",
            },
            "confirmReload": {"type": "boolean", "const": True},
        },
    },
}
