import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (relative) => fs.readFileSync(path.join(root, relative), "utf8");

const hook = read("src/hooks/use-approval-execution.ts");
const types = read("src/lib/chat-types.ts");
const apiTypes = read("src/lib/api/types.ts");
const runtimeApi = read("src/lib/api/agent-runtime.ts");
const history = read("src/lib/conversation-utils.ts");
const scopedCard = read("src/components/approvals/scoped-pending-approval-card.tsx");
const pendingStrip = read("src/components/approvals/pending-approvals-strip.tsx");
const inlineCard = read("src/components/chat/conversation-card.tsx");
const inlineTimeline = read("src/components/chat/conversation-timeline.tsx");
const app = read("src/App.tsx");

assert.match(hook, /if \(approval\.goalDeliveryId\?\.trim\(\)\) \{\s*return;/);
assert.match(hook, /const payload = await requestApprovalRevision/);
assert.match(hook, /if \(!payload\.ok\)/);
assert.ok(hook.indexOf("const payload = await requestApprovalRevision") < hook.indexOf("appendToChat(activeChatId"));
assert.doesNotMatch(hook, /approval\.arguments|approval\.paramsSummary|approval\.preview/);
assert.match(hook, /type: "approval_revision"/);
assert.match(hook, /status: "awaiting_user_input"/);
assert.match(hook, /payload\.execution\?\.status === "needs_user_action"/);
assert.match(hook, /payload\.execution\.outcome\?\.summary/);
assert.match(hook, /error: payload\.execution\?\.error \|\| completionNotice/);
assert.match(hook, /const resultChatId = taskSessionId \? ownerChatId : activeChatId;/);
assert.match(hook, /appendToChat\(resultChatId/);
const approveStart = hook.indexOf("async function approveShell");
const approveEnd = hook.indexOf("async function rejectShell");
const approve = hook.slice(approveStart, approveEnd);
assert.doesNotMatch(approve, /appendToChat\(activeChatId/);
assert.match(app, /const pendingApprovalItems = \(agentApprovals \?\? \[\]\)\.filter\(\s*\(item\) => item\.status === "pending",?\s*\)/);
assert.doesNotMatch(app, /item\.status === "pending" \|\| item\.status === "approved"/);
assert.match(scopedCard, /approval\.status === "pending"/);
assert.match(pendingStrip, /approval\.status === "pending"/);
const rejectStart = hook.indexOf("async function rejectShell");
const rejectEnd = hook.indexOf("function clearApprovalAction");
const reject = hook.slice(rejectStart, rejectEnd);
assert.match(reject, /if \(!payload\.ok\)/);
assert.ok(reject.indexOf("if (!payload.ok)") < reject.indexOf("appendContinuation"));
const continuationStart = hook.indexOf("function appendContinuation");
const continuationEnd = hook.indexOf("function pendingApprovalForResponse");
const continuation = hook.slice(continuationStart, continuationEnd);
assert.ok(continuationStart >= 0 && continuationEnd > continuationStart);
assert.match(continuation, /response\.sessionId \|\| response\.session_id/);
assert.match(continuation, /chatIdForSessionId\(ownerSessionId\)/);
assert.match(continuation, /appendToChat\(ownerChatId/);
assert.doesNotMatch(continuation, /appendToChat\(activeChatId/);
assert.match(apiTypes, /taskContext\?: \{[\s\S]*sessionId\?: string;/);
assert.match(runtimeApi, /continuation\?: AgentRuntimeResponse/);
assert.match(types, /type: "approval_revision"/);
assert.match(types, /approvalId: string;\s*targetTool: string;\s*requestedAt: string;\s*reason: string;\s*note: string;\s*status: "awaiting_user_input";/s);
assert.doesNotMatch(history.slice(history.indexOf("export function buildChatHistory"), history.indexOf("export function visibleAgentDialogueText")), /approval_revision/);
assert.match(scopedCard, /!approval\.goalDeliveryId\?\.trim\(\)/);
assert.match(inlineTimeline, /!approval\.goalDeliveryId\?\.trim\(\)/);
assert.match(inlineCard, /data-approval-revision=/);

console.log("approval revision UI contract passed");
