from pathlib import Path
import json, os, shutil, subprocess
import pytest
ROOT=Path(__file__).resolve().parents[1]

def test_shader_adapter_capability_runtime(tmp_path):
 dotnet=shutil.which('dotnet'); pf=Path(os.environ.get('ProgramFiles','C:/Program Files')); sdk=sorted((pf/'dotnet/sdk').glob('3.1.*/Roslyn/bincore/csc.dll')); refs=sorted((pf/'dotnet/packs/Microsoft.NETCore.App.Ref').glob('3.1.*/ref/netcoreapp3.1'))
 if not dotnet or not sdk or not refs: pytest.skip('Local SDK3.1 compiler/reference pack required')
 ref=os.environ.get('VRCFORGE_SHADER_ADAPTER_GIT_REF','').strip();
 if ref:
  got=subprocess.run(['git','show',f'{ref}:Assets/VRCForge/Editor/ShaderMaterialAdapters.cs'],cwd=ROOT,capture_output=True,text=True,check=True); source=got.stdout
 else: source=(ROOT/'Assets/VRCForge/Editor/ShaderMaterialAdapters.cs').read_text(encoding='utf-8-sig')
 product='namespace VRCForge.Editor { public sealed class MaterialPropertyValue { public string type; public object value; public bool writable; } }\n'+'\n'.join(x for x in source.splitlines() if not x.startswith('using '))
 stubs=r'''namespace UnityEngine { public struct Color { public float r,g,b,a; } public struct Vector4 { public float x,y,z,w; public float this[int i]{get=>i==0?x:i==1?y:i==2?z:w;set{if(i==0)x=value;else if(i==1)y=value;else if(i==2)z=value;else w=value;}} } public struct LocalKeyword { public bool isValid; } public sealed class Shader { public string name; public Dictionary<string,ShaderPropertyType> Props=new Dictionary<string,ShaderPropertyType>(); public int FindPropertyIndex(string n)=>Props.ContainsKey(n)?Props.Keys.ToList().IndexOf(n)+1:-1; public ShaderPropertyType GetPropertyType(int i){return Props.Values.ElementAt(i-1);} public KeywordSpace keywordSpace=new KeywordSpace(); } public enum ShaderPropertyType { Color,Vector,Float,Range,Texture } public sealed class KeywordSpace { public LocalKeyword FindKeyword(string n)=>new LocalKeyword(); } public class Material { public Shader shader; Dictionary<string,object> vals=new Dictionary<string,object>(); public bool HasProperty(string n)=>shader!=null&&shader.Props.ContainsKey(n); public Color GetColor(string n)=>vals.ContainsKey(n)?(Color)vals[n]:new Color(); public Vector4 GetVector(string n)=>vals.ContainsKey(n)?(Vector4)vals[n]:new Vector4(); public float GetFloat(string n)=>vals.ContainsKey(n)?(float)vals[n]:0; public void SetColor(string n,Color v){vals[n]=v;} public void SetVector(string n,Vector4 v){vals[n]=v;} public void SetFloat(string n,float v){vals[n]=v;} public void EnableKeyword(string n){} public void DisableKeyword(string n){} } public static class ColorUtility { public static string ToHtmlStringRGBA(Color c)=>"000000FF"; public static bool TryParseHtmlString(string s,out Color c){c=new Color();return true;} } public static class Mathf { public static bool Approximately(float a,float b)=>a==b; public static float Round(float a)=>a; public static float Clamp(float a,float x,float y)=>a<x?x:a>y?y:a; } }
'''
 runner=r'''class Probe { static int f; static void C(bool x,string n){System.Console.WriteLine((x?"PASS ":"FAIL ")+n);if(!x)f++;} static UnityEngine.Shader S(params (string,UnityEngine.ShaderPropertyType)[] ps){var s=new UnityEngine.Shader{name="Arbitrary"};foreach(var p in ps)s.Props[p.Item1]=p.Item2;return s;} public static int Main(){var generic=new VRCForge.Editor.GenericShaderAdapter();var wrongFirst=new UnityEngine.Material{shader=S(("_Color",UnityEngine.ShaderPropertyType.Float),("_BaseColor",UnityEngine.ShaderPropertyType.Color))};C(generic.ReadSupportedProperties(wrongFirst).ContainsKey("base_color"),"wrong first alias skips to compatible color");var texture=new UnityEngine.Material{shader=S(("_ShadowStrength",UnityEngine.ShaderPropertyType.Texture))};C(!generic.ReadSupportedProperties(texture).ContainsKey("shadow_strength"),"texture does not satisfy float mapping");var lil=new VRCForge.Editor.LilToonShaderAdapter();var vector=new UnityEngine.Material{shader=S(("_MainTexHSVG",UnityEngine.ShaderPropertyType.Vector))};C(lil.ReadSupportedProperties(vector).ContainsKey("main_saturation"),"vector property supports vector component mapping");var raw=new UnityEngine.Material{shader=S(("_CustomRaw",UnityEngine.ShaderPropertyType.Float))};C(generic.Supports(raw)&&generic.ReadSupportedProperties(raw).Count==0,"generic accepts arbitrary raw-only shader with empty semantic list");C(!generic.Supports(null)&&!generic.Supports(new UnityEngine.Material{shader=null}),"generic rejects null material or shader");return f==0?0:1;}}'''
 cs=tmp_path/'Probe.cs';cs.write_text('using System;using System.Linq;using System.Collections.Generic;using System.Globalization;using UnityEngine;'+stubs+product+runner,encoding='utf-8');dll=tmp_path/'Probe.dll';cmd=[dotnet,str(sdk[-1]),'-nologo','-target:exe','-nostdlib+','-langversion:8.0',f'-out:{dll}']+[f'-r:{x}' for x in refs[-1].glob('*.dll')]+[str(cs)];built=subprocess.run(cmd,capture_output=True,text=True,timeout=60);assert built.returncode==0,built.stdout+built.stderr;(tmp_path/'Probe.runtimeconfig.json').write_text(json.dumps({'runtimeOptions':{'tfm':'netcoreapp3.1','framework':{'name':'Microsoft.NETCore.App','version':'3.1.0'}}}));run=subprocess.run([dotnet,str(dll)],capture_output=True,text=True,timeout=30);assert run.returncode==0,run.stdout+run.stderr;assert run.stdout.count('PASS ')==5,run.stdout


